function [material,gen_rule] = name2struct(basefile)
%NAME2STRUCT 输入文件名称，输出与该模拟相对应的组分结构体
%自定义文件需要:物性分析,单位集,切换公用工程
global utility_set
switch basefile
    case 'case3.bkp'
        material = struct( ...
            'name', {'NC3','IC4','NC4','IC5','NC5','CC5','IC61','IC62' 'IC63' 'NC6' 'CC61' 'IC7' 'C6H6' 'CC62' 'NC7'}, ...
            'product',{0 0 0 1 1 2 2 0 0 0 0 0 0 0 0}); % case3,C5
        gen_rule{1} = struct( ...
            'name1',    {"default" "IC4"}, ...
            'name2',    {"default" "IC5"}, ...
            'P',        {1.5        5.3}, ... 
            'recovl',   {0.999      []}, ...
            'recovh',   {0.001      []});
        utility_set=1;
end
end